spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1GB
      enabled: true
      max-request-size: 2GB

server:
  port: 80
  servlet:
    context-path: /file
    session:
      timeout: 3600
    encoding:
      force-request: true
      charset: utf-8
      force-response: true
      enabled: true
      force: true

  tomcat:
    background-processor-delay: 30
    uri-encoding: UTF-8
    max-connections: 1000



